schedules:
  - cron: "0 0 * * 0"
    displayName: Weekly midnight build

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .azure/pipelines/coverity.yml

pr: none

variables:
  - group: Coverity

jobs:
  - job: Analyze
    displayName: Analyze with Coverity
    steps:
      - checkout: self
        submodules: true
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - script: yarn --cwd trestle-server/ install
        displayName: Install Dependencies
      - script: |
          wget -q https://scan.coverity.com/download/linux64 --post-data "token=$(COVERITY_TOKEN)&project=nickrobison%2Ftrestle" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        displayName: Download Coverity
      - script: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int --fs-capture-search trestle-server/src/main/webapp/src/app ./gradlew assemble
        displayName: Run Coverity
      - script: |
          tar czvf trestle.tgz cov-int
          curl \
            --form token=$(COVERITY_TOKEN) \
            --form email=nick@nickrobison.com \
            --form file=@trestle.tgz \
            --form version=$(Build.SourceVersion) \
            --form description="`git rev-parse --short HEAD`" \
            https://scan.coverity.com/builds?project=nickrobison%2Ftrestle
        displayName: Upload results
