schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master

trigger:
  paths:
    include:
      - .azure/pipelines/coverity.yml

variables:
  - group: Coverity
    name: COVERITY_TOKEN

jobs:
  - job: Analyze
    displayName: Analyze with Coverity
    steps:
      - checkout: self
        submodules: true
#      - task: Cache@2
#        displayName: Cache Gradle local repo
#        inputs:
#          key: 'gradle | "$(Agent.OS)" | "$(jdkVersion)" | **/build.gradle'
#          restoreKeys: |
#            gradle | "$(Agent.OS)" | "$(jdkVersion)"
#            gradle | "$(Agent.OS)"
#            gradle
#          path: $(MAVEN_CACHE_FOLDER)
#      - task: Cache@2
#        displayName: Cache Yarn dependencies
#        inputs:
#          key: 'yarn | "$(Agent.OS)" | trestle-server/yarn.lock'
#          restoreKeys: |
#            yarn | "$(Agent.OS)"
#            yarn
#          path: $(YARN_CACHE_FOLDER)
      - script: |
          wget -q https://scan.coverity.com/download/java/linux64 --post-data "token=$(COVERITY_TOKEN)&project=CDCgov/prime-simplereport" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        displayName:
      - task: Gradle@2
        displayName: Build Java
        inputs:
          gradleOptions: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(jdkVersion)
          tasks: 'assemble'
          jdkArchitectureOption: 'x64'
      - script: yarn --cwd trestle-server/ install
        displayName: Install Dependencies


