#!/bin/bash
while [[ $# -gt 0 ]]
do

case ${1} in
  "cloc")
  cloc --exclude-dir=$(tr '\n' ',' < ./.clocignore) .
  ;;
  "docker")
#  Build trestle-server
  echo "Building Java project"
  rm -rf trestle-server/node_modules
  mvn clean package -DskipTests -pl trestle-server -am -T3
#  Build the docker images
  echo "Building GraphDB Docker image"
  docker build --build-arg version=8.4.1 -t docker.nickrobison.com:5000/graphdb:8.4.1-free docker/graphdb
  echo "Building Trestle Server docker image"
#  Copy the ontology file into the trestle-server directory
  cp ././../trestle-ontology/trestle.owl ./trestle-server/trestle.owl
  docker build --build-arg version="0.8.0-SNAPSHOT" -t docker.nickrobison.com:5000/trestle-server:0.8.0-SNAPSHOT -f trestle-server/Dockerfile trestle-server/
#  Remove the ontology file
  rm ./trestle-server/trestle.owl
  echo "Finished!"
  ;;
esac
shift
done
