version: '3'

services:
  graphdb:
    image: ontotext/graphdb:10.3.3
    ports:
      - "7200:7200"

  trestle:
    depends_on:
      - graphdb
    image: nickrobison/trestle-server
    environment:
      CS: http://graphdb:7200
      CONFIG_FILE: ${CONFIG_FILE:-/app/resources/config.ci.yml}
    ports:
      - "8080:8080"
      - "8087:8087"
