import {NgModule} from "@angular/core";
import {
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatChipsModule,
    MatDialogModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatOptionModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatTabsModule,
    MatToolbarModule
} from "@angular/material";

@NgModule({
    imports: [MatButtonModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatMenuModule,
        MatSidenavModule,
        MatCardModule,
        MatGridListModule,
        MatChipsModule,
        MatButtonToggleModule,
        MatToolbarModule,
        MatListModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MatInputModule,
        MatTabsModule,
        MatProgressBarModule,
        MatFormFieldModule,
        MatOptionModule],
    exports: [MatButtonModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatMenuModule,
        MatSidenavModule,
        MatCardModule,
        MatGridListModule,
        MatChipsModule,
        MatButtonToggleModule,
        MatToolbarModule,
        MatListModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MatInputModule,
        MatTabsModule,
        MatProgressBarModule,
        MatFormFieldModule,
        MatOptionModule]
})
export class MaterialModule {
}