import { NgModule } from "@angular/core";
import {
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatChipsModule,
    MatDialogModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatOptionModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatTabsModule,
    MatToolbarModule, MatTooltipModule
} from "@angular/material";

@NgModule({
    imports: [MatButtonModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatMenuModule,
        MatSidenavModule,
        MatCardModule,
        MatGridListModule,
        MatChipsModule,
        MatButtonToggleModule,
        MatToolbarModule,
        MatTooltipModule,
        MatListModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MatSelectModule,
        MatInputModule,
        MatTabsModule,
        MatProgressBarModule,
        MatFormFieldModule,
        MatOptionModule,
        MatExpansionModule],
    exports: [MatButtonModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatMenuModule,
        MatSidenavModule,
        MatCardModule,
        MatGridListModule,
        MatChipsModule,
        MatButtonToggleModule,
        MatToolbarModule,
        MatTooltipModule,
        MatListModule,
        MatIconModule,
        MatProgressSpinnerModule,
        MatSelectModule,
        MatInputModule,
        MatTabsModule,
        MatProgressBarModule,
        MatFormFieldModule,
        MatOptionModule,
        MatExpansionModule]
})
export class MaterialModule {
}